language: objective-c
osx_image: xcode10.1

env:
  - SCHEME="YoutubeDirectLinkExtractor-macOS"  DESTINATION="arch=x86_64"
  - SCHEME="YoutubeDirectLinkExtractor-iOS"    DESTINATION="platform=iOS Simulator,name=iPhone SE,OS=12.1"

script:
  - xcodebuild clean test -scheme "$SCHEME" -destination "$DESTINATION"
